/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutFarmsRouteImport } from './routes/_layout/farms'
import { Route as LayoutFarmerListRouteImport } from './routes/_layout/farmer-list'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutBarnPageRouteImport } from './routes/_layout/barn-page'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutFarmsRoute = LayoutFarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFarmerListRoute = LayoutFarmerListRouteImport.update({
  id: '/farmer-list',
  path: '/farmer-list',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBarnPageRoute = LayoutBarnPageRouteImport.update({
  id: '/barn-page',
  path: '/barn-page',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/barn-page': typeof LayoutBarnPageRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/farmer-list': typeof LayoutFarmerListRoute
  '/farms': typeof LayoutFarmsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/barn-page': typeof LayoutBarnPageRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/farmer-list': typeof LayoutFarmerListRoute
  '/farms': typeof LayoutFarmsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/barn-page': typeof LayoutBarnPageRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/farmer-list': typeof LayoutFarmerListRoute
  '/_layout/farms': typeof LayoutFarmsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/barn-page' | '/dashboard' | '/farmer-list' | '/farms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/barn-page' | '/dashboard' | '/farmer-list' | '/farms'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/barn-page'
    | '/_layout/dashboard'
    | '/_layout/farmer-list'
    | '/_layout/farms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/farms': {
      id: '/_layout/farms'
      path: '/farms'
      fullPath: '/farms'
      preLoaderRoute: typeof LayoutFarmsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/farmer-list': {
      id: '/_layout/farmer-list'
      path: '/farmer-list'
      fullPath: '/farmer-list'
      preLoaderRoute: typeof LayoutFarmerListRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/barn-page': {
      id: '/_layout/barn-page'
      path: '/barn-page'
      fullPath: '/barn-page'
      preLoaderRoute: typeof LayoutBarnPageRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBarnPageRoute: typeof LayoutBarnPageRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutFarmerListRoute: typeof LayoutFarmerListRoute
  LayoutFarmsRoute: typeof LayoutFarmsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBarnPageRoute: LayoutBarnPageRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutFarmerListRoute: LayoutFarmerListRoute,
  LayoutFarmsRoute: LayoutFarmsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
